hosts = [
  { name: 'vm-web', hostname: 'vm.web.local', box: 'centos/7', mem: 1024, cpu: 2, netint: 1 },
  { name: 'vm-db', hostname: 'vm.db.local', box: 'centos/7', mem: 1024, cpu: 2, netint: 2 }
]


Vagrant.configure('2') do |config|
  hosts.each do |host|
    config.vm.define host[:name] do |node|
      node.vm.box = host[:box]
      node.vm.hostname = host[:hostname]
      node.vm.provider :virtualbox do |v|
        v.memory = host[:mem]
        v.cpus = host[:cpu]
      end

      if host[:netint] == 1
        node.vm.network "private_network", ip: "192.168.33.134"
        node.vm.provision "shell", inline: "sudo echo '192.168.33.133 chef.srv.local' >> /etc/hosts"
      end

      if host[:netint] == 2
        node.vm.network "private_network", ip: "192.168.33.135"
        node.vm.provision "shell", inline: "sudo echo '192.168.33.133 chef.srv.local' >> /etc/hosts"
      end

    end
  end
end
